### ISSUE TITLE
Fix border in cards when hover

### ISSUE THREAD

**Issue by reyesjerez** [reyesjerez/access_auj#1]
When the mouse hover over the cards, they get smaller. 
Fix this so the cards don't change their size when hover.

**Comment by reyesjerez** [comment]
To fix this bug, you will have to:
- Create a new branch on this repository.
- Search on ./src/scss/App.scss for .cards for line 60.
- Delete line 60.
- Update GitHub
- Create "Pull Request"

**Comment by elialcodes** [comment]
Hi Reyes,
I did it,
just tell me if something is wrong,
Noelia
